[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-src https://sites.google.com https://calendar.app.google; child-src https://sites.google.com https://calendar.app.google;"
