// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smyppttkzitjmakvohkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteXBwdHRreml0am1ha3ZvaGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDUyNjgsImV4cCI6MjA2NDYyMTI2OH0.9dQkzo5JbsM0e6dqd1QzXziE0dWSg47L77Yd7mDyG5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);