// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_REACT_APP_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_REACT_APP_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) {
  throw new Error("VITE_REACT_APP_SUPABASE_URL is not defined");
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("VITE_REACT_APP_SUPABASE_ANON_KEY is not defined");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);